In [ ]:
import requests
from bs4 import BeautifulSoup

url = "https://www.pricecharting.com/console/pokemon-mega-evolution"
resp = requests.get(url)
print("Código de respuesta HTTP:", resp.status_code)

Código de respuesta HTTP: 200

In [ ]:
# Creamos el objeto BeautifulSoup para interpretar el HTML
soup = BeautifulSoup(resp.text, "html.parser")

# Buscamos la tabla con id="games_table"
tabla = soup.find("table", id="games_table")

# Comprobamos si la tabla se ha encontrado correctamente
print("¿Tabla encontrada?:", tabla is not None)

¿Tabla encontrada?: True

In [ ]:
# 1) Obtenemos todas las filas (<tr>) del cuerpo de la tabla
filas = tabla.tbody.find_all("tr")

# 2) Vemos cuántas filas/cartos hay en este set
print("Número de filas (cartas) encontradas:", len(filas))

# 3) Cogemos la primera fila de la tabla
primera_fila = filas[0]

# 4) Mostramos el HTML completo de esa primera fila de forma legible
print(primera_fila.prettify())

Número de filas (cartas) encontradas: 50
<tr data-product="10669978" id="product-10669978">
 <td class="image">
  <div>
   <a href="https://www.pricecharting.com/game/pokemon-mega-evolution/mega-lucario-ex-188" title="10669978">
    <img class="photo" loading="lazy" src="https://storage.googleapis.com/images.pricecharting.com/hgvcsnv7zu4qfapt/60.jpg">
    </img>
   </a>
  </div>
 </td>
 <td class="title" title="10669978">
  <a href="/game/pokemon-mega-evolution/mega-lucario-ex-188">
   Mega Lucario Ex #188
  </a>
 </td>
 <td class="price numeric used_price">
  <span class="js-price">
   $352.67
  </span>
 </td>
 <td class="price numeric cib_price">
  <span class="js-price">
   $422.28
  </span>
 </td>
 <td class="price numeric new_price">
  <span class="js-price">
   $1,043.56
  </span>
 </td>
 <td class="add_to container">
  <ul class="add_to collection">
   <li class="add_to collection">
    <ul class="list" data-product-id="10669978">
     <li class="list-item">
      <a class="js-add-one-click" data-product-id="10669978" href="#" rel="nofollow">
       <span class="small-desktop-visible">
        + Collection
       </span>
       In One Click
      </a>
     </li>
     <li class="list-item">
      <a href="/publish-offer?product=10669978&amp;add-to-collection=1" rel="nofollow">
       <span class="small-desktop-visible">
        + Collection
       </span>
       With Details
      </a>
     </li>
     <li class="list-item small-desktop-visible-cell">
      <a class="js-add-bid" href="#" rel="nofollow">
       + Wishlist
      </a>
     </li>
    </ul>
    <span class="blue button small">
     +
     <span class="small-desktop-hidden">
      Collection
     </span>
    </span>
   </li>
  </ul>
  <ul class="add_to wishlist" data-product-id="10669978">
   <li class="add_to wishlist">
    <span class="blue button small js-add-bid">
     +
     <span class="small-desktop-hidden">
      Wishlist
     </span>
    </span>
   </li>
  </ul>
 </td>
</tr>

In [ ]:
# EXTRAER DE LA PRIMERA FILA LOS 4 DATOS IMPORTANTES

# Nombre
nombre = primera_fila.find("td", class_="title").get_text(strip=True)

# Ungraded
ungraded = primera_fila.find("td", class_="used_price").get_text(strip=True)

# Grade 9
grade9 = primera_fila.find("td", class_="cib_price").get_text(strip=True)

# PSA 10
psa10 = primera_fila.find("td", class_="new_price").get_text(strip=True)

print("Nombre  :", nombre)
print("Ungraded:", ungraded)
print("Grade 9 :", grade9)
print("PSA 10  :", psa10)

Nombre  : Mega Lucario Ex #188
Ungraded: $352.67
Grade 9 : $422.28
PSA 10  : $1,043.56

In [ ]:
import pandas as pd  # por si aún no lo has importado

# Función auxiliar para no rompernos si falta alguna celda
def extraer_celda(fila, class_name):
    celda = fila.find("td", class_=class_name)
    if celda is not None:
        return celda.get_text(strip=True)
    else:
        return None

# Lista donde guardaremos todas las cartas
cartas = []

# Recorremos TODAS las filas de la tabla
for fila in filas:
    nombre = extraer_celda(fila, "title")
    ungraded = extraer_celda(fila, "used_price")
    grade9 = extraer_celda(fila, "cib_price")
    psa10 = extraer_celda(fila, "new_price")

    # Solo añadimos la fila si tiene nombre (para evitar filas raras/vacías)
    if nombre is not None:
        cartas.append({
            "nombre": nombre,
            "ungraded": ungraded,
            "grade9": grade9,
            "psa10": psa10
        })

# Convertimos la lista de diccionarios en un DataFrame
df = pd.DataFrame(cartas)

# Vemos las primeras filas para comprobar
df.head()

                   nombre ungraded   grade9      psa10
0    Mega Lucario Ex #188  $352.67  $422.28  $1,043.56
1    Mega Lucario Ex #179  $212.51  $319.00    $516.01
2  Mega Gardevoir ex #178  $193.65  $269.50    $499.17
3     Mega Latias ex #181  $125.00  $207.50    $415.00
4  Mega Gardevoir Ex #187  $308.59  $293.01    $737.44

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
ruta_csv = '/content/drive/MyDrive/pokemon_mega_evolution.csv'
df.to_csv(ruta_csv, index=False)

print("CSV guardado en:", ruta_csv)

CSV guardado en: /content/drive/MyDrive/pokemon_mega_evolution.csv

In [ ]:
url_cat = "https://www.pricecharting.com/category/pokemon-cards"

resp_cat = requests.get(url_cat)
print("Código de respuesta categoría:", resp_cat.status_code)

soup_cat = BeautifulSoup(resp_cat.text, "html.parser")

Código de respuesta categoría: 200

In [ ]:
# Buscamos todos los enlaces <a> dentro de la página de categorías
enlaces = soup_cat.find_all("a")

urls_sets = []

for a in enlaces:
    href = a.get("href", "")
    # Nos interesan solo los enlaces que empiezan por "/console/pokemon"
    if href.startswith("/console/pokemon"):
        url_completa = "https://www.pricecharting.com" + href
        if url_completa not in urls_sets:
            urls_sets.append(url_completa)

# Vemos cuántos sets hemos encontrado y los primeros 10
print("Número de sets encontrados:", len(urls_sets))
urls_sets[:10]

Número de sets encontrados: 302

['https://www.pricecharting.com/console/pokemon-promo',
 'https://www.pricecharting.com/console/pokemon-mega-evolution',
 'https://www.pricecharting.com/console/pokemon-prismatic-evolutions',
 'https://www.pricecharting.com/console/pokemon-destined-rivals',
 'https://www.pricecharting.com/console/pokemon-scarlet-&-violet-151',
 'https://www.pricecharting.com/console/pokemon-base-set',
 'https://www.pricecharting.com/console/pokemon-surging-sparks',
 'https://www.pricecharting.com/console/pokemon-crown-zenith',
 'https://www.pricecharting.com/console/pokemon-celebrations',
 'https://www.pricecharting.com/console/pokemon-japanese-promo']

#Funcion para scrapear sets

In [ ]:
def scrapear_set(url_set):
    """
    Descarga un set de PriceCharting (URL /console/...)
    y devuelve una lista de diccionarios con las cartas de ese set.
    """
    print("Scrapeando set:", url_set)

    resp = requests.get(url_set)
    if resp.status_code != 200:
        print("  Error HTTP:", resp.status_code)
        return []  # devolvemos lista vacía si hay fallo

    soup = BeautifulSoup(resp.text, "html.parser")

    tabla = soup.find("table", id="games_table")
    if tabla is None:
        print("  No se encontró tabla en este set.")
        return []

    filas = tabla.tbody.find_all("tr")

    cartas_set = []

    for fila in filas:
        nombre   = extraer_celda(fila, "title")
        ungraded = extraer_celda(fila, "used_price")
        grade9   = extraer_celda(fila, "cib_price")
        psa10    = extraer_celda(fila, "new_price")

        if nombre is not None:
            cartas_set.append({
                "nombre": nombre,
                "ungraded": ungraded,
                "grade9": grade9,
                "psa10": psa10
            })

    print("  Cartas en este set:", len(cartas_set))
    return cartas_set

In [ ]:
lista_cartas = scrapear_set("https://www.pricecharting.com/console/pokemon-mega-evolution")

Scrapeando set: https://www.pricecharting.com/console/pokemon-mega-evolution
  Cartas en este set: 50

In [ ]:
todas_las_cartas = []

In [ ]:
import time
from tqdm import tqdm


print("Iniciando scraping…")

for url_set in tqdm(urls_sets):
    try:
        cartas_set = scrapear_set(url_set)
        todas_las_cartas.extend(cartas_set)

        # Pausa para no saturar al servidor
        time.sleep(0.5)

    except Exception as e:
        print("Error en:", url_set)
        print("Detalle del error:", e)

Iniciando scraping…

  0%|          | 0/302 [00:00<?, ?it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-promo
  Cartas en este set: 50

  0%|          | 1/302 [00:01<06:07,  1.22s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mega-evolution
  Cartas en este set: 50

  1%|          | 2/302 [00:02<05:11,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-prismatic-evolutions
  Cartas en este set: 50

  1%|          | 3/302 [00:03<05:09,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-destined-rivals
  Cartas en este set: 50

  1%|▏         | 4/302 [00:04<05:06,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-scarlet-&-violet-151
  Cartas en este set: 50

  2%|▏         | 5/302 [00:05<05:38,  1.14s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-base-set
  Cartas en este set: 50

  2%|▏         | 6/302 [00:06<05:23,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-surging-sparks
  Cartas en este set: 50

  2%|▏         | 7/302 [00:07<05:07,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-crown-zenith
  Cartas en este set: 50

  3%|▎         | 8/302 [00:08<05:41,  1.16s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-celebrations
  Cartas en este set: 50

  3%|▎         | 9/302 [00:10<05:42,  1.17s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-promo
  Cartas en este set: 50

  3%|▎         | 10/302 [00:11<05:41,  1.17s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-black-bolt
  Cartas en este set: 50

  4%|▎         | 11/302 [00:12<05:17,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-journey-together
  Cartas en este set: 50

  4%|▍         | 12/302 [00:13<05:13,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-evolving-skies
  Cartas en este set: 50

  4%|▍         | 13/302 [00:14<04:57,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-white-flare
  Cartas en este set: 50

  5%|▍         | 14/302 [00:15<04:58,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-paldean-fates
  Cartas en este set: 50

  5%|▍         | 15/302 [00:16<04:49,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-evolutions
  Cartas en este set: 50

  5%|▌         | 16/302 [00:17<04:42,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-paradox-rift
  Cartas en este set: 50

  6%|▌         | 17/302 [00:18<05:03,  1.06s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-twilight-masquerade
  Cartas en este set: 50

  6%|▌         | 18/302 [00:19<04:56,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-inferno-x
  Cartas en este set: 50

  6%|▋         | 19/302 [00:20<05:03,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-obsidian-flames
  Cartas en este set: 50

  7%|▋         | 20/302 [00:21<04:47,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-mega-dream-ex

  7%|▋         | 21/302 [00:21<03:47,  1.24it/s]

Error en: https://www.pricecharting.com/console/pokemon-japanese-mega-dream-ex
Detalle del error: 'NoneType' object has no attribute 'find_all'
Scrapeando set: https://www.pricecharting.com/console/pokemon-phantasmal-flames
  Cartas en este set: 50

  7%|▋         | 22/302 [00:22<04:05,  1.14it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-csgc
  Cartas en este set: 2

  8%|▊         | 23/302 [00:23<04:02,  1.15it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-gem-pack-3
  Cartas en este set: 50

  8%|▊         | 24/302 [00:24<04:06,  1.13it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-1999-topps-movie
  Cartas en este set: 50

  8%|▊         | 25/302 [00:25<04:07,  1.12it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-1999-topps-movie-evolution
  Cartas en este set: 37

  9%|▊         | 26/302 [00:26<04:08,  1.11it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-1999-topps-tv
  Cartas en este set: 50

  9%|▉         | 27/302 [00:27<04:12,  1.09it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-2000-topps-chrome
  Cartas en este set: 50

  9%|▉         | 28/302 [00:28<04:28,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-2000-topps-tv
  Cartas en este set: 50

 10%|▉         | 29/302 [00:29<04:22,  1.04it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-2020-battle-academy
  Cartas en este set: 50

 10%|▉         | 30/302 [00:30<04:23,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-ancient-origins
  Cartas en este set: 50

 10%|█         | 31/302 [00:31<04:30,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-aquapolis
  Cartas en este set: 50

 11%|█         | 32/302 [00:32<04:49,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-arceus
  Cartas en este set: 50

 11%|█         | 33/302 [00:33<04:38,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-astral-radiance
  Cartas en este set: 50

 11%|█▏        | 34/302 [00:34<04:27,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-breakpoint
  Cartas en este set: 50

 12%|█▏        | 35/302 [00:35<04:17,  1.04it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-breakthrough
  Cartas en este set: 50

 12%|█▏        | 36/302 [00:36<04:10,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-base-set-2
  Cartas en este set: 50

 12%|█▏        | 37/302 [00:37<04:18,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-battle-styles
  Cartas en este set: 50

 13%|█▎        | 38/302 [00:38<04:09,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-best-of-game
  Cartas en este set: 24

 13%|█▎        | 39/302 [00:39<04:04,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-black-&-white
  Cartas en este set: 50

 13%|█▎        | 40/302 [00:39<03:59,  1.09it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-boundaries-crossed
  Cartas en este set: 50

 14%|█▎        | 41/302 [00:40<03:56,  1.11it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-brilliant-stars
  Cartas en este set: 50

 14%|█▍        | 42/302 [00:41<04:08,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-burger-king
  Cartas en este set: 50

 14%|█▍        | 43/302 [00:42<04:15,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-burning-shadows
  Cartas en este set: 50

 15%|█▍        | 44/302 [00:43<04:12,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-call-of-legends
  Cartas en este set: 50

 15%|█▍        | 45/302 [00:44<04:14,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-celestial-storm
  Cartas en este set: 50

 15%|█▌        | 46/302 [00:45<04:16,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-champion%27s-path
  Cartas en este set: 50

 16%|█▌        | 47/302 [00:46<04:05,  1.04it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chilling-reign
  Cartas en este set: 50

 16%|█▌        | 48/302 [00:47<03:56,  1.07it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-151-collect
  Cartas en este set: 50

 16%|█▌        | 49/302 [00:48<03:53,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-cs4ac
  Cartas en este set: 50

 17%|█▋        | 50/302 [00:49<03:49,  1.10it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-cs4bc
  Cartas en este set: 50

 17%|█▋        | 51/302 [00:50<04:01,  1.04it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-cs5ac
  Cartas en este set: 16

 17%|█▋        | 52/302 [00:51<03:50,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-csm2ac
  Cartas en este set: 16

 18%|█▊        | 53/302 [00:52<03:42,  1.12it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-csm2bc
  Cartas en este set: 16

 18%|█▊        | 54/302 [00:53<03:39,  1.13it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-csm2cc
  Cartas en este set: 18

 18%|█▊        | 55/302 [00:53<03:41,  1.11it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-csv4c
  Cartas en este set: 3

 19%|█▊        | 56/302 [00:54<03:34,  1.15it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-gem-pack
  Cartas en este set: 50

 19%|█▉        | 57/302 [00:55<03:38,  1.12it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-gem-pack-2
  Cartas en este set: 50

 19%|█▉        | 58/302 [00:56<03:52,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-chinese-promo
  Cartas en este set: 29

 20%|█▉        | 59/302 [00:57<04:02,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-cosmic-eclipse
  Cartas en este set: 50

 20%|█▉        | 60/302 [00:59<04:34,  1.13s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-crimson-invasion
  Cartas en este set: 50

 20%|██        | 61/302 [01:00<04:28,  1.11s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-crystal-guardians
  Cartas en este set: 50

 21%|██        | 62/302 [01:01<04:16,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-dark-explorers
  Cartas en este set: 50

 21%|██        | 63/302 [01:02<04:20,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-darkness-ablaze
  Cartas en este set: 50

 21%|██        | 64/302 [01:03<04:32,  1.15s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-delta-species
  Cartas en este set: 50

 22%|██▏       | 65/302 [01:04<04:17,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-deoxys
  Cartas en este set: 50

 22%|██▏       | 66/302 [01:05<04:10,  1.06s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-detective-pikachu
  Cartas en este set: 27

 22%|██▏       | 67/302 [01:07<04:29,  1.15s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-diamond-&-pearl
  Cartas en este set: 50

 23%|██▎       | 68/302 [01:08<04:26,  1.14s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-double-crisis
  Cartas en este set: 50

 23%|██▎       | 69/302 [01:09<04:14,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-dragon
  Cartas en este set: 50

 23%|██▎       | 70/302 [01:10<04:07,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-dragon-frontiers
  Cartas en este set: 50

 24%|██▎       | 71/302 [01:11<03:58,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-dragon-majesty
  Cartas en este set: 50

 24%|██▍       | 72/302 [01:12<03:55,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-dragon-vault
  Cartas en este set: 34

 24%|██▍       | 73/302 [01:13<03:53,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-dragons-exalted
  Cartas en este set: 50

 25%|██▍       | 74/302 [01:14<03:45,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-ex-latias-&-latios
  Cartas en este set: 18

 25%|██▍       | 75/302 [01:15<03:45,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-emerald
  Cartas en este set: 50

 25%|██▌       | 76/302 [01:16<03:48,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-emerging-powers
  Cartas en este set: 50

 25%|██▌       | 77/302 [01:17<03:53,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-expedition
  Cartas en este set: 50

 26%|██▌       | 78/302 [01:18<03:52,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-fates-collide
  Cartas en este set: 50

 26%|██▌       | 79/302 [01:19<03:46,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-fire-red-&-leaf-green
  Cartas en este set: 50

 26%|██▋       | 80/302 [01:20<03:41,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-flashfire
  Cartas en este set: 50

 27%|██▋       | 81/302 [01:21<03:39,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-forbidden-light
  Cartas en este set: 50

 27%|██▋       | 82/302 [01:22<03:38,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-fossil
  Cartas en este set: 50

 27%|██▋       | 83/302 [01:23<03:51,  1.06s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-furious-fists
  Cartas en este set: 50

 28%|██▊       | 84/302 [01:24<03:40,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-fusion-strike
  Cartas en este set: 50

 28%|██▊       | 85/302 [01:25<03:32,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-generations
  Cartas en este set: 50

 28%|██▊       | 86/302 [01:26<03:26,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-go
  Cartas en este set: 50

 29%|██▉       | 87/302 [01:27<03:29,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-great-encounters
  Cartas en este set: 50

 29%|██▉       | 88/302 [01:28<03:24,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-guardians-rising
  Cartas en este set: 50

 29%|██▉       | 89/302 [01:29<03:23,  1.04it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-gym-challenge
  Cartas en este set: 50

 30%|██▉       | 90/302 [01:29<03:21,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-gym-heroes
  Cartas en este set: 50

 30%|███       | 91/302 [01:31<03:36,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-heartgold-&-soulsilver
  Cartas en este set: 50

 30%|███       | 92/302 [01:32<03:35,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-hidden-fates
  Cartas en este set: 50

 31%|███       | 93/302 [01:33<03:43,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-hidden-legends
  Cartas en este set: 50

 31%|███       | 94/302 [01:34<03:46,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-holon-phantoms
  Cartas en este set: 50

 31%|███▏      | 95/302 [01:35<03:40,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-10th-movie-commemoration-promo
  Cartas en este set: 13

 32%|███▏      | 96/302 [01:36<03:28,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-1996-carddass
  Cartas en este set: 50

 32%|███▏      | 97/302 [01:37<03:27,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-1997-carddass
  Cartas en este set: 50

 32%|███▏      | 98/302 [01:38<03:20,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-2002-mcdonald%27s
  Cartas en este set: 33

 33%|███▎      | 99/302 [01:39<03:23,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-2005-gift-box
  Cartas en este set: 26

 33%|███▎      | 100/302 [01:40<03:23,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-20th-anniversary
  Cartas en este set: 50

 33%|███▎      | 101/302 [01:41<03:22,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-25th-anniversary-collection
  Cartas en este set: 50

 34%|███▍      | 102/302 [01:42<03:23,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-25th-anniversary-golden-box
  Cartas en este set: 17

 34%|███▍      | 103/302 [01:43<03:14,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-25th-anniversary-promo
  Cartas en este set: 26

 34%|███▍      | 104/302 [01:44<03:21,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-alter-genesis
  Cartas en este set: 50

 35%|███▍      | 105/302 [01:45<03:19,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-amazing-volt-tackle
  Cartas en este set: 50

 35%|███▌      | 106/302 [01:46<03:13,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-ancient-roar
  Cartas en este set: 50

 35%|███▌      | 107/302 [01:47<03:12,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-awakening-legends
  Cartas en este set: 50

 36%|███▌      | 108/302 [01:48<03:36,  1.12s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-awakening-psychic-king
  Cartas en este set: 50

 36%|███▌      | 109/302 [01:49<03:37,  1.13s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-bandit-ring
  Cartas en este set: 50

 36%|███▋      | 110/302 [01:50<03:24,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-battle-partners
  Cartas en este set: 50

 37%|███▋      | 111/302 [01:51<03:16,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-battle-region
  Cartas en este set: 50

 37%|███▋      | 112/302 [01:52<03:23,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-best-of-xy
  Cartas en este set: 50

 37%|███▋      | 113/302 [01:53<03:14,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-black-bolt
  Cartas en este set: 50

 38%|███▊      | 114/302 [01:54<03:13,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-blue-sky-stream
  Cartas en este set: 50

 38%|███▊      | 115/302 [01:55<03:05,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-cd-promo
  Cartas en este set: 13

 38%|███▊      | 116/302 [01:56<02:57,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-challenge-from-the-darkness
  Cartas en este set: 50

 39%|███▊      | 117/302 [01:57<03:05,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-charizard-vmax-starter-set
  Cartas en este set: 22

 39%|███▉      | 118/302 [01:58<03:11,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-clash-of-the-blue-sky
  Cartas en este set: 50

 39%|███▉      | 119/302 [01:59<03:10,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-classic-blastoise
  Cartas en este set: 32

 40%|███▉      | 120/302 [02:00<03:04,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-classic-charizard
  Cartas en este set: 34

 40%|████      | 121/302 [02:01<02:58,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-classic-venusaur
  Cartas en este set: 31

 40%|████      | 122/302 [02:02<02:50,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-clay-burst
  Cartas en este set: 50

 41%|████      | 123/302 [02:03<02:53,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-crimson-haze
  Cartas en este set: 50

 41%|████      | 124/302 [02:04<02:48,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-crossing-the-ruins
  Cartas en este set: 50

 41%|████▏     | 125/302 [02:05<02:43,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-cyber-judge
  Cartas en este set: 50

 42%|████▏     | 126/302 [02:06<02:38,  1.11it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-dark-phantasma
  Cartas en este set: 50

 42%|████▏     | 127/302 [02:07<02:36,  1.12it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-darkness-and-to-light
  Cartas en este set: 50

 42%|████▏     | 128/302 [02:08<02:41,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-detective-pikachu
  Cartas en este set: 26

 43%|████▎     | 129/302 [02:09<02:38,  1.09it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-double-blaze
  Cartas en este set: 50

 43%|████▎     | 130/302 [02:10<02:41,  1.07it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-double-crisis
  Cartas en este set: 50

 43%|████▎     | 131/302 [02:10<02:36,  1.09it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-dream-league
  Cartas en este set: 50

 44%|████▎     | 132/302 [02:11<02:36,  1.09it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-dream-shine-collection
  Cartas en este set: 38

 44%|████▍     | 133/302 [02:13<02:44,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-ex-battle-boost
  Cartas en este set: 50

 44%|████▍     | 134/302 [02:14<02:45,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-eevee-heroes
  Cartas en este set: 50

 45%|████▍     | 135/302 [02:14<02:39,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-emerald-break
  Cartas en este set: 50

 45%|████▌     | 136/302 [02:15<02:37,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-expansion-pack
  Cartas en este set: 50

 45%|████▌     | 137/302 [02:16<02:40,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-expedition-expansion-pack
  Cartas en este set: 50

 46%|████▌     | 138/302 [02:17<02:35,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-fusion-arts
  Cartas en este set: 50

 46%|████▌     | 139/302 [02:18<02:30,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-future-flash
  Cartas en este set: 50

 46%|████▋     | 140/302 [02:19<02:27,  1.10it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-gg-end
  Cartas en este set: 50

 47%|████▋     | 141/302 [02:20<02:26,  1.10it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-gx-battle-boost
  Cartas en este set: 50

 47%|████▋     | 142/302 [02:21<02:31,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-gx-ultra-shiny
  Cartas en este set: 50

 47%|████▋     | 143/302 [02:22<02:26,  1.09it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-gengar-vmax-high-class
  Cartas en este set: 12

 48%|████▊     | 144/302 [02:23<02:20,  1.13it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-glory-of-team-rocket
  Cartas en este set: 50

 48%|████▊     | 145/302 [02:23<02:19,  1.12it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-go
  Cartas en este set: 50

 48%|████▊     | 146/302 [02:25<02:24,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-gold-silver-new-world
  Cartas en este set: 50

 49%|████▊     | 147/302 [02:26<02:32,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-golden-sky-silvery-ocean
  Cartas en este set: 50

 49%|████▉     | 148/302 [02:27<02:31,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-heat-wave-arena
  Cartas en este set: 50

 49%|████▉     | 149/302 [02:27<02:25,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-holon-phantom
  Cartas en este set: 50

 50%|████▉     | 150/302 [02:28<02:20,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-holon-research
  Cartas en este set: 50

 50%|█████     | 151/302 [02:29<02:22,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-incandescent-arcana
  Cartas en este set: 50

 50%|█████     | 152/302 [02:31<02:39,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-intense-fight-in-the-destroyed-sky
  Cartas en este set: 50

 51%|█████     | 153/302 [02:32<02:35,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-jungle
  Cartas en este set: 50

 51%|█████     | 154/302 [02:33<02:32,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-leaders%27-stadium
  Cartas en este set: 50

 51%|█████▏    | 155/302 [02:34<02:28,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-legendary-shine-collection
  Cartas en este set: 29

 52%|█████▏    | 156/302 [02:35<02:28,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-lost-abyss
  Cartas en este set: 50

 52%|█████▏    | 157/302 [02:36<02:34,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-m-charizard-ex-mega-battle-deck
  Cartas en este set: 23

 52%|█████▏    | 158/302 [02:37<02:57,  1.23s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-mask-of-change
  Cartas en este set: 50

 53%|█████▎    | 159/302 [02:39<02:48,  1.18s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-matchless-fighter
  Cartas en este set: 50

 53%|█████▎    | 160/302 [02:40<02:41,  1.14s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-mega-brave
  Cartas en este set: 50

 53%|█████▎    | 161/302 [02:41<02:39,  1.13s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-mega-starter-deck-diancie-ex
  Cartas en este set: 24

 54%|█████▎    | 162/302 [02:42<02:37,  1.13s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-mega-starter-deck-gengar-ex
  Cartas en este set: 24

 54%|█████▍    | 163/302 [02:43<02:34,  1.11s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-mega-symphonia
  Cartas en este set: 50

 54%|█████▍    | 164/302 [02:44<02:25,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-miracle-twins
  Cartas en este set: 50

 55%|█████▍    | 165/302 [02:45<02:18,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-mysterious-mountains
  Cartas en este set: 50

 55%|█████▍    | 166/302 [02:46<02:13,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-mystery-of-the-fossils
  Cartas en este set: 50

 55%|█████▌    | 167/302 [02:47<02:16,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-night-unison
  Cartas en este set: 50

 56%|█████▌    | 168/302 [02:48<02:11,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-night-wanderer
  Cartas en este set: 50

 56%|█████▌    | 169/302 [02:49<02:13,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-offense-and-defense-of-the-furthest-ends
  Cartas en este set: 50

 56%|█████▋    | 170/302 [02:50<02:17,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-old-maid
  Cartas en este set: 40

 57%|█████▋    | 171/302 [02:51<02:14,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-paradigm-trigger
  Cartas en este set: 50

 57%|█████▋    | 172/302 [02:52<02:20,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-paradise-dragona
  Cartas en este set: 50

 57%|█████▋    | 173/302 [02:53<02:27,  1.14s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-phantom-gate
  Cartas en este set: 50

 58%|█████▊    | 174/302 [02:54<02:17,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-player%27s-club
  Cartas en este set: 31

 58%|█████▊    | 175/302 [02:55<02:11,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-pokekyun-collection
  Cartas en este set: 33

 58%|█████▊    | 176/302 [02:56<02:05,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-premium-champion-pack
  Cartas en este set: 50

 59%|█████▊    | 177/302 [02:57<02:09,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-raging-surf
  Cartas en este set: 50

 59%|█████▉    | 178/302 [02:58<02:08,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-remix-bout
  Cartas en este set: 50

 59%|█████▉    | 179/302 [02:59<02:04,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-rising-fist
  Cartas en este set: 50

 60%|█████▉    | 180/302 [03:00<02:04,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-rocket-gang
  Cartas en este set: 50

 60%|█████▉    | 181/302 [03:01<02:01,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-rocket-gang-strikes-back
  Cartas en este set: 50

 60%|██████    | 182/302 [03:02<02:09,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-ruler-of-the-black-flame
  Cartas en este set: 50

 61%|██████    | 183/302 [03:03<02:07,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-svg-special-set
  Cartas en este set: 7

 61%|██████    | 184/302 [03:04<01:59,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-scarlet-&-violet-151
  Cartas en este set: 50

 61%|██████▏   | 185/302 [03:05<01:56,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-scarlet-ex
  Cartas en este set: 50

 62%|██████▏   | 186/302 [03:06<01:53,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-shining-darkness
  Cartas en este set: 50

 62%|██████▏   | 187/302 [03:07<01:57,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-shining-legends
  Cartas en este set: 50

 62%|██████▏   | 188/302 [03:09<02:03,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-shiny-collection
  Cartas en este set: 26

 63%|██████▎   | 189/302 [03:10<02:18,  1.23s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-shiny-star-v
  Cartas en este set: 50

 63%|██████▎   | 190/302 [03:11<02:09,  1.16s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-shiny-treasure-ex
  Cartas en este set: 50

 63%|██████▎   | 191/302 [03:12<02:04,  1.12s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-sky-legend
  Cartas en este set: 50

 64%|██████▎   | 192/302 [03:13<02:01,  1.10s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-snow-hazard
  Cartas en este set: 50

 64%|██████▍   | 193/302 [03:14<01:54,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-southern-island
  Cartas en este set: 22

 64%|██████▍   | 194/302 [03:15<01:47,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-space-juggler
  Cartas en este set: 50

 65%|██████▍   | 195/302 [03:16<01:47,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-space-time
  Cartas en este set: 50

 65%|██████▍   | 196/302 [03:17<01:48,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-split-earth
  Cartas en este set: 50

 65%|██████▌   | 197/302 [03:18<01:47,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-star-birth
  Cartas en este set: 50

 66%|██████▌   | 198/302 [03:19<01:46,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-start-deck-100
  Cartas en este set: 50

 66%|██████▌   | 199/302 [03:20<01:43,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-stellar-miracle
  Cartas en este set: 50

 66%|██████▌   | 200/302 [03:21<01:44,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-super-electric-breaker
  Cartas en este set: 50

 67%|██████▋   | 201/302 [03:22<01:44,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-tag-all-stars
  Cartas en este set: 50

 67%|██████▋   | 202/302 [03:23<01:39,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-tag-bolt
  Cartas en este set: 50

 67%|██████▋   | 203/302 [03:24<01:36,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-tag-team-starter-set
  Cartas en este set: 9

 68%|██████▊   | 204/302 [03:25<01:34,  1.04it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-terastal-festival
  Cartas en este set: 50

 68%|██████▊   | 205/302 [03:26<01:34,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-the-town-on-no-map
  Cartas en este set: 50

 68%|██████▊   | 206/302 [03:27<01:33,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-time-gazer
  Cartas en este set: 50

 69%|██████▊   | 207/302 [03:28<01:38,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-topsun
  Cartas en este set: 50

 69%|██████▉   | 208/302 [03:29<01:38,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-triplet-beat
  Cartas en este set: 50

 69%|██████▉   | 209/302 [03:30<01:37,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-vmax-climax
  Cartas en este set: 50

 70%|██████▉   | 210/302 [03:31<01:39,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-vs
  Cartas en este set: 50

 70%|██████▉   | 211/302 [03:33<01:38,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-vstar-universe
  Cartas en este set: 50

 70%|███████   | 212/302 [03:33<01:32,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-vending
  Cartas en este set: 50

 71%|███████   | 213/302 [03:34<01:30,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-violet-ex
  Cartas en este set: 50

 71%|███████   | 214/302 [03:35<01:26,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-web
  Cartas en este set: 50

 71%|███████   | 215/302 [03:36<01:26,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-white-flare
  Cartas en este set: 50

 72%|███████▏  | 216/302 [03:37<01:27,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-wild-blaze
  Cartas en este set: 50

 72%|███████▏  | 217/302 [03:38<01:24,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-wild-force
  Cartas en este set: 50

 72%|███████▏  | 218/302 [03:39<01:24,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-wind-from-the-sea
  Cartas en este set: 50

 73%|███████▎  | 219/302 [03:40<01:24,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-world-championships-2023
  Cartas en este set: 16

 73%|███████▎  | 220/302 [03:41<01:21,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-japanese-yamabuki-city-gym
  Cartas en este set: 32

 73%|███████▎  | 221/302 [03:43<01:27,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-jungle
  Cartas en este set: 50

 74%|███████▎  | 222/302 [03:44<01:29,  1.12s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-korean-eevee-heroes
  Cartas en este set: 19

 74%|███████▍  | 223/302 [03:45<01:22,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-korean-promo
  Cartas en este set: 50

 74%|███████▍  | 224/302 [03:46<01:18,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-korean-terastal-festival-ex
  Cartas en este set: 17

 75%|███████▍  | 225/302 [03:47<01:15,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-legend-maker
  Cartas en este set: 50

 75%|███████▍  | 226/302 [03:48<01:16,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-legendary-collection
  Cartas en este set: 50

 75%|███████▌  | 227/302 [03:49<01:16,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-legendary-treasures
  Cartas en este set: 50

 75%|███████▌  | 228/302 [03:50<01:13,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-legends-awakened
  Cartas en este set: 50

 76%|███████▌  | 229/302 [03:51<01:14,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-lost-origin
  Cartas en este set: 50

 76%|███████▌  | 230/302 [03:52<01:12,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-lost-thunder
  Cartas en este set: 50

 76%|███████▋  | 231/302 [03:53<01:14,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-majestic-dawn
  Cartas en este set: 50

 77%|███████▋  | 232/302 [03:54<01:17,  1.11s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mcdonalds-2016
  Cartas en este set: 12

 77%|███████▋  | 233/302 [03:55<01:15,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mcdonalds-2018
  Cartas en este set: 12

 77%|███████▋  | 234/302 [03:56<01:11,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mcdonalds-2019
  Cartas en este set: 12

 78%|███████▊  | 235/302 [03:57<01:09,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mcdonalds-2021
  Cartas en este set: 50

 78%|███████▊  | 236/302 [03:59<01:20,  1.22s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mcdonalds-2022
  Cartas en este set: 17

 78%|███████▊  | 237/302 [04:00<01:12,  1.12s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mcdonalds-2023
  Cartas en este set: 16

 79%|███████▉  | 238/302 [04:01<01:09,  1.08s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mcdonalds-2024
  Cartas en este set: 16

 79%|███████▉  | 239/302 [04:02<01:05,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-mysterious-treasures
  Cartas en este set: 50

 79%|███████▉  | 240/302 [04:03<01:07,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-neo-destiny
  Cartas en este set: 50

 80%|███████▉  | 241/302 [04:04<01:03,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-neo-discovery
  Cartas en este set: 50

 80%|████████  | 242/302 [04:05<01:03,  1.06s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-neo-genesis
  Cartas en este set: 50

 80%|████████  | 243/302 [04:06<01:02,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-neo-revelation
  Cartas en este set: 50

 81%|████████  | 244/302 [04:07<01:03,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-next-destinies
  Cartas en este set: 50

 81%|████████  | 245/302 [04:08<01:02,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-noble-victories
  Cartas en este set: 50

 81%|████████▏ | 246/302 [04:09<00:58,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-pop-series-1
  Cartas en este set: 25

 82%|████████▏ | 247/302 [04:10<00:54,  1.00it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-pop-series-2
  Cartas en este set: 25

 82%|████████▏ | 248/302 [04:11<00:52,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-pop-series-3
  Cartas en este set: 25

 82%|████████▏ | 249/302 [04:12<00:54,  1.02s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-pop-series-4
  Cartas en este set: 25

 83%|████████▎ | 250/302 [04:13<00:53,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-pop-series-5
  Cartas en este set: 25

 83%|████████▎ | 251/302 [04:15<01:05,  1.28s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-paldea-evolved
  Cartas en este set: 50

 83%|████████▎ | 252/302 [04:16<00:58,  1.17s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-phantom-forces
  Cartas en este set: 50

 84%|████████▍ | 253/302 [04:17<00:54,  1.11s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-pikachu-libre-&-suicune
  Cartas en este set: 41

 84%|████████▍ | 254/302 [04:18<00:51,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-plasma-blast
  Cartas en este set: 50

 84%|████████▍ | 255/302 [04:19<00:53,  1.13s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-plasma-freeze
  Cartas en este set: 50

 85%|████████▍ | 256/302 [04:20<00:51,  1.12s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-plasma-storm
  Cartas en este set: 50

 85%|████████▌ | 257/302 [04:21<00:50,  1.12s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-platinum
  Cartas en este set: 50

 85%|████████▌ | 258/302 [04:22<00:50,  1.15s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-power-keepers
  Cartas en este set: 50

 86%|████████▌ | 259/302 [04:23<00:48,  1.12s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-primal-clash
  Cartas en este set: 50

 86%|████████▌ | 260/302 [04:24<00:45,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-rebel-clash
  Cartas en este set: 50

 86%|████████▋ | 261/302 [04:25<00:42,  1.04s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-rising-rivals
  Cartas en este set: 50

 87%|████████▋ | 262/302 [04:26<00:41,  1.03s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-roaring-skies
  Cartas en este set: 50

 87%|████████▋ | 263/302 [04:27<00:38,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-ruby-&-sapphire
  Cartas en este set: 50

 87%|████████▋ | 264/302 [04:29<00:41,  1.09s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-rumble
  Cartas en este set: 16

 88%|████████▊ | 265/302 [04:30<00:41,  1.13s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-sandstorm
  Cartas en este set: 50

 88%|████████▊ | 266/302 [04:31<00:44,  1.23s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-scarlet-&-violet
  Cartas en este set: 50

 88%|████████▊ | 267/302 [04:32<00:41,  1.18s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-scarlet-&-violet-energy
  Cartas en este set: 50

 89%|████████▊ | 268/302 [04:33<00:39,  1.15s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-secret-wonders
  Cartas en este set: 50

 89%|████████▉ | 269/302 [04:35<00:37,  1.14s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-shining-fates
  Cartas en este set: 50

 89%|████████▉ | 270/302 [04:36<00:35,  1.11s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-shining-legends
  Cartas en este set: 50

 90%|████████▉ | 271/302 [04:37<00:32,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-shrouded-fable
  Cartas en este set: 50

 90%|█████████ | 272/302 [04:38<00:31,  1.06s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-silver-tempest
  Cartas en este set: 50

 90%|█████████ | 273/302 [04:39<00:30,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-skyridge
  Cartas en este set: 50

 91%|█████████ | 274/302 [04:40<00:29,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-southern-islands
  Cartas en este set: 19

 91%|█████████ | 275/302 [04:41<00:28,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-steam-siege
  Cartas en este set: 50

 91%|█████████▏| 276/302 [04:42<00:26,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-stellar-crown
  Cartas en este set: 50

 92%|█████████▏| 277/302 [04:43<00:24,  1.04it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-stormfront
  Cartas en este set: 50

 92%|█████████▏| 278/302 [04:43<00:22,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-sun-&-moon
  Cartas en este set: 50

 92%|█████████▏| 279/302 [04:45<00:23,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-supreme-victors
  Cartas en este set: 50

 93%|█████████▎| 280/302 [04:46<00:21,  1.01it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-sword-&-shield
  Cartas en este set: 50

 93%|█████████▎| 281/302 [04:46<00:20,  1.02it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-tcg-classic-blastoise-deck
  Cartas en este set: 35

 93%|█████████▎| 282/302 [04:47<00:18,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-tcg-classic-charizard-deck
  Cartas en este set: 36

 94%|█████████▎| 283/302 [04:49<00:20,  1.07s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-tcg-classic-venusaur-deck
  Cartas en este set: 35

 94%|█████████▍| 284/302 [04:50<00:18,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-team-magma-&-team-aqua
  Cartas en este set: 50

 94%|█████████▍| 285/302 [04:51<00:17,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-team-rocket
  Cartas en este set: 50

 95%|█████████▍| 286/302 [04:52<00:15,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-team-rocket-returns
  Cartas en este set: 50

 95%|█████████▌| 287/302 [04:52<00:14,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-team-up
  Cartas en este set: 50

 95%|█████████▌| 288/302 [04:54<00:14,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-temporal-forces
  Cartas en este set: 50

 96%|█████████▌| 289/302 [04:54<00:12,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-trick-or-trade-2022
  Cartas en este set: 33

 96%|█████████▌| 290/302 [04:55<00:11,  1.04it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-trick-or-trade-2023
  Cartas en este set: 33

 96%|█████████▋| 291/302 [04:56<00:10,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-trick-or-trade-2024
  Cartas en este set: 33

 97%|█████████▋| 292/302 [04:57<00:09,  1.08it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-triumphant
  Cartas en este set: 50

 97%|█████████▋| 293/302 [04:58<00:08,  1.05it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-ultra-prism
  Cartas en este set: 50

 97%|█████████▋| 294/302 [04:59<00:08,  1.05s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-unbroken-bonds
  Cartas en este set: 50

 98%|█████████▊| 295/302 [05:01<00:07,  1.06s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-undaunted
  Cartas en este set: 50

 98%|█████████▊| 296/302 [05:01<00:06,  1.01s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-unified-minds
  Cartas en este set: 50

 98%|█████████▊| 297/302 [05:02<00:04,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-unleashed
  Cartas en este set: 50

 99%|█████████▊| 298/302 [05:03<00:04,  1.00s/it]

Scrapeando set: https://www.pricecharting.com/console/pokemon-unseen-forces
  Cartas en este set: 50

 99%|█████████▉| 299/302 [05:04<00:02,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-vivid-voltage
  Cartas en este set: 50

 99%|█████████▉| 300/302 [05:05<00:01,  1.03it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-world-championships-2023
  Cartas en este set: 50

100%|█████████▉| 301/302 [05:06<00:00,  1.06it/s]

Scrapeando set: https://www.pricecharting.com/console/pokemon-xy
  Cartas en este set: 50

100%|██████████| 302/302 [05:07<00:00,  1.02s/it]

# Crear dataframe

In [ ]:
df_total = pd.DataFrame(todas_las_cartas)
df_total.head()
print(len(df_total))

NameError: name 'todas_las_cartas' is not defined

In [ ]:
ruta_csv = '/content/drive/MyDrive/todas_las_cartas_pokemon.csv'
df_total.to_csv(ruta_csv, index=False)

print("CSV guardado en:", ruta_csv)

NameError: name 'df_total' is not defined

In [ ]:


ruta = "/content/drive/MyDrive/Python/Cartas_Pokemon/Lista_pokemon_oficial_limpia.csv"

df_lista_total = pd.read_csv(ruta, sep=";", decimal=",")
df.head()

                   nombre ungraded   grade9      psa10
0    Mega Lucario Ex #188  $352.67  $422.28  $1,043.56
1    Mega Lucario Ex #179  $212.51  $319.00    $516.01
2  Mega Gardevoir ex #178  $193.65  $269.50    $499.17
3     Mega Latias ex #181  $125.00  $207.50    $415.00
4  Mega Gardevoir Ex #187  $308.59  $293.01    $737.44

In [ ]:
filtro_ungraded = df_lista_total[df_lista_total["ungraded"] < 50]
filtro_ungraded.head()

                     nombre  ungraded  grade9   psa10  Beneficio
3  Charizard VStar #SWSH262     49.46   79.00  782.50     733.04
4                Eevee #173     12.23   19.50   90.63      78.40
6            Charmander #44     32.97   65.00  325.05     292.08
7   Charizard VMax #SWSH261     32.50   64.11  490.00     457.50
8    Lucario VSTAR #SWSH291     11.00   21.25  111.78     100.78

In [ ]:
len(filtro_ungraded)

11134

In [ ]:
filtro_beneficio = filtro_ungraded[filtro_ungraded["Beneficio"] > 100]
filtro_beneficio.head()

                     nombre  ungraded  grade9   psa10  Beneficio
3  Charizard VStar #SWSH262     49.46   79.00  782.50     733.04
6            Charmander #44     32.97   65.00  325.05     292.08
7   Charizard VMax #SWSH261     32.50   64.11  490.00     457.50
8    Lucario VSTAR #SWSH291     11.00   21.25  111.78     100.78
9               Snorlax #51     13.85   29.96  160.36     146.51

In [ ]:
len(filtro_beneficio)

3360

In [ ]:
ruta_csv = '/content/drive/MyDrive/Python/Cartas_Pokemon/todas_las_cartas_pokemon_filtradas.csv'
filtro_beneficio.to_csv(ruta_csv, index=False)

print("CSV guardado en:", ruta_csv)

CSV guardado en: /content/drive/MyDrive/Python/Cartas_Pokemon/todas_las_cartas_pokemon_filtradas.csv